# Generated by Django 5.0.7 on 2024-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Init', models.CharField(max_length=50)),
                ('GIP', models.CharField(max_length=50)),
                ('Comment_GIP', models.CharField(max_length=50)),
                ('initiator', models.DateField()),
            ],
        ),
    ]
