# Generated by Django 5.0.7 on 2024-08-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table1',
            options={'managed': False},
        ),
    ]
