# Generated by Django 5.0.7 on 2024-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_table1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=150)),
                ('mokap', models.CharField(max_length=150)),
                ('manufactured', models.DateTimeField()),
                ('initiator', models.CharField(max_length=100)),
                ('date_agreement_gip', models.DateTimeField()),
                ('gip', models.CharField(max_length=100)),
                ('gip_comment', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'Site',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
