# Generated by Django 5.0.7 on 2024-08-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_site_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False},
        ),
    ]
